// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetUserByAuthTypeAndAuthId(ctx context.Context, arg GetUserByAuthTypeAndAuthIdParams) (sql.NullInt32, error)
}

var _ Querier = (*Queries)(nil)
