// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getUserByAuthTypeAndAuthId = `-- name: GetUserByAuthTypeAndAuthId :one
SELECT user_id FROM users_auths WHERE auth_type = $1 AND auth_id = $2
`

type GetUserByAuthTypeAndAuthIdParams struct {
	AuthType sql.NullString
	AuthID   sql.NullString
}

func (q *Queries) GetUserByAuthTypeAndAuthId(ctx context.Context, arg GetUserByAuthTypeAndAuthIdParams) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getUserByAuthTypeAndAuthId, arg.AuthType, arg.AuthID)
	var user_id sql.NullInt32
	err := row.Scan(&user_id)
	return user_id, err
}
